endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

zuul:
  sensitiveHeaders: Access-Control-Allow-Origin,Access-Control-Allow-Credentials,www-authenticate
  ignoredServices: '*'
  routes:
    orientdb:
      path: /orientdb/**
      stripPrefix: true
      serviceId: orientdb

orientdb:
  ribbon:
    listOfServers: ${ORIENTDB_RIBBON_LIST_OF_SERVERS:localhost:2480}
    ServerListRefreshInterval: 15000

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
ribbon:
  ConnectTimeout: 200 
  ReadTimeout: 60000
  eureka:
    enabled: false

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    server:
    waitTimeInMsWhenSyncEmpty: 0
    healthcheck:
      enabled: false

logging:
  level:
    ROOT: INFO
    org.springframework.web: INFO